//objeto1
#define LARGURA_MESA TAM_BLOCO
#define ALTURA_MESA LARGURA_MESA/2.0
#define COMPRIMENTO_MESA LARGURA_MESA/2.0
#define GROSSURA_MESA LARGURA_MESA/10.0
#define GROSSURA_PE GROSSURA_MESA/2.0

//robô
#define TAM_CABECA 4
#define LARGURA_CORPO 6
#define ALTURA_CORPO 10	
#define TAM_PE 4
#define TAM_TOTAL 20
#define RAIO_PESCOCO TAM_CABECA/3.0
#define RAIO_OLHOS TAM_CABECA/8.0
#define LARGURA_SORRISO TAM_CABECA/2.0
#define ALTURA_SORRISO RAIO_OLHOS*1.5
#define COMPRIMENTO_ORELHAS TAM_CABECA/3.0
#define RAIO_ANTENA RAIO_OLHOS/2.0
#define COMPRIMENTO_BRACO ALTURA_CORPO/2.5
#define GROSSURA_BRACO ALTURA_CORPO/15.0


//mundo do jogo
#define MAX 400.0
#define FPS 30
#define TAM_BLOCO 20
#define TAM_MAPA 15
#define TAM_MUNDO 1000
